"""SYNTHETIC worlds for testing the pipeline's mechanics.

Rainfall, terrain and landslides here are generated by formulas. Nothing measured in
these worlds is a result about real landslides, and none of it may be quoted as one.
"""

from __future__ import annotations

import json
from datetime import date, timedelta

import numpy as np
from rasta_ml.events import Event
from rasta_ml.grid import Grid
from rasta_ml.manifest import Manifest, parse_manifest
from rasta_ml.sources import LEAD_DAYS


def manifest_document(**overrides) -> dict:
    document = {
        "schema_version": "rasta-ml-manifest-v1",
        "name": "synthetic-test-world",
        "question": "SYNTHETIC: does the pipeline run end to end?",
        "unit": {"cell_deg": 0.25, "day": "UTC"},
        "region": {
            "name": "Synthetic hills",
            "bbox": [91.0, 25.0, 92.0, 26.0],
            "country": "India",
            "states": ["Meghalaya"],
        },
        "period": ["2007-01-01", "2010-12-31"],
        "split": {
            "train_years": [2007, 2008],
            "validate_years": [2009, 2009],
            "test_years": [2010, 2010],
            "spatial_block_deg": 0.5,
            "spatial_folds": 2,
        },
        "labels": {
            "triggers": ["rain", "downpour"],
            "max_location_error_km": 25,
            "observed_area": "cells with a training-year event",
            "min_test_positives": 5,
        },
        "sources": {
            key: {
                "title": f"SYNTHETIC {key}",
                "url": "",
                "licence": "generated",
                "licence_confirmed": True,
            }
            for key in ("rainfall", "terrain", "events")
        },
        "seed": 7,
        "gate": {
            "metric": "pr_auc",
            "interval": 0.95,
            "bootstrap_resamples": 200,
            "bootstrap_unit": "day",
            "rule": "SYNTHETIC test rule text.",
        },
    }
    document.update(overrides)
    return document


def manifest(**overrides) -> Manifest:
    return parse_manifest(json.dumps(manifest_document(**overrides)).encode())


def world(
    m: Manifest, *, seed: int = 11, signal: bool = True
) -> tuple[np.ndarray, date, dict, list[Event], Grid]:
    """Rain, terrain and events for every cell of the manifest's region.

    With ``signal`` the events follow rain and slope; without it they are drawn at
    the same rate regardless of either, so no model should find anything.
    """

    rng = np.random.default_rng(seed)
    grid = Grid.for_region(m.region, m.cell_deg)
    first = m.start - timedelta(days=LEAD_DAYS)
    days = (m.end - first).days + 1
    season = 1 + 2 * np.clip(
        np.sin((np.arange(days) % 365) / 365 * 2 * np.pi - 1.2), 0, None
    )
    rain = (
        rng.gamma(0.6, 8.0, size=(days, grid.ny, grid.nx)) * season[:, None, None]
    ).astype(np.float32)

    terrain = {}
    for cell in range(len(grid)):
        p90 = float(rng.uniform(8, 40))
        terrain[cell] = {
            "slope_mean_deg": p90 * 0.5,
            "slope_p90_deg": p90,
            "steep_fraction": max(0.0, (p90 - 25) / 40),
            "relief_m": p90 * 30,
        }

    events: list[Event] = []
    for cell in range(len(grid)):
        row, col = grid.row_col(cell)
        series = rain[:, row, col].astype(np.float64)
        totals = np.convolve(series, np.ones(3))[: series.size]
        if signal:
            logits = (
                -10.5 + 1.3 * np.log1p(totals) + 0.07 * terrain[cell]["slope_p90_deg"]
            )
        else:
            logits = np.full(series.size, -5.4)
        hits = rng.random(series.size) < 1 / (1 + np.exp(-logits))
        lat, lon = grid.centre(cell)
        for index in np.flatnonzero(hits):
            day = first + timedelta(days=int(index))
            if day < m.start:
                continue
            events.append(
                Event(
                    ref=f"synthetic-{cell}-{index}",
                    day=day,
                    lat=lat + float(rng.uniform(-0.1, 0.1)),
                    lon=lon + float(rng.uniform(-0.1, 0.1)),
                    location_error_km=5.0,
                    trigger="rain",
                    country="India",
                    state="Meghalaya",
                    source="synthetic generator",
                )
            )
    return rain, first, terrain, events, grid
